name: Catalog Service Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/catalog/**'
      - '.github/workflows/catalog-tests.yml'
  push:
    branches: [ main ]
    paths:
      - 'backend/catalog/**'
      - '.github/workflows/catalog-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend/catalog

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/catalog/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
